### ISSUE TITLE
Add Table of Contents to README

### ISSUE THREAD

**Issue by ttu** [ttu/dotnet-fake-json-server#10]
Tools to create toc e.g.:
https://github.com/ekalinin/github-markdown-toc
https://ecotrust-canada.github.io/markdown-toc/

Toc should look like this:

## Table of Contents

<Details>

- [Test](#test)
  * [TestA](#testa)
- [Test2](#test2)

</Details>
  
## Test

lorem ipsum

### TestA

lorem ipsum

**Comment by leplaekevin** [comment]
i made a toc.
i'll send a pull request.

**Comment by ttu** [comment]
Added in #16
