### ISSUE TITLE
Using Id located somewhere else

### ISSUE THREAD

**Issue by Icaroto** [ttu/dotnet-fake-json-server#11]
Hi,

Is there a way to reference an idea inside a collection rather than a straight forward property?
Using your "users" as an example:

```
"users": [
    {
      "id": 1,
      "name": "James",
      "age": 40,
      "location": "NY",
      "work": {
        "name": "ACME",
        "location": "NY",
        "rating": 2.3
      }
]
```

To access it I can user users/1 but what if my Id is inside one of the propeties? for eg:

```
"users": [
    {
      "name": "James",
      "age": 40,
      "location": "NY",
      "work": {
        "id": 1,
        "name": "ACME",
        "location": "NY",
        "rating": 2.3
      }
    }
]
```

Is there a way to access this record with "users/{id} but when it gets executed it points to "users/work/{id}" ? 

Thanks

**Comment by ttu** [comment]
Hi,

As all queries are parsed dynamically, querying from the child property without defining all identifiers in the path is not possible.

Correct way to query users based on the child's property is like this:

```sh
$ curl http://localhost:57602/api/users?work.id=1
```
