### ISSUE TITLE
Option to create a new Object

### ISSUE THREAD

**Issue by zimbres** [ttu/dotnet-fake-json-server#114]
Is there an option to create a new object? Thanks!

**Comment by ttu** [comment]
Hi! Yes, you can post any data you, with any name (example has `abcd`) and it will be stored to JSON-file and can be fetched with the name you defined.

```sh
# Add new data
curl -H "Accept: application/json" -H "Content-type: application/json" -X POST -d '{ "value": "1", "description": "hello", "random": "data" }' http://localhost:57602/api/abcd/

# Fetch created data
curl http://localhost:57602/api/abcd/0

```

If you have any other questions, just let me know :+1:

**Comment by zimbres** [comment]
Awesome! Thanks a lot!!!

**Comment by ttu** [comment]
Opened an issue for documentation update: https://github.com/ttu/dotnet-fake-json-server/issues/118
