### ISSUE TITLE
Add JSON Patch support for updates

### ISSUE THREAD

**Issue by ttu** [ttu/dotnet-fake-json-server#17]
Add support for JSON Patch

http://jsonpatch.com/

**Comment by zlzshowtime** [comment]
Hey Im interested and picking this issue up.

**Comment by ttu** [comment]
@zlzshowtime great! Just let me know of you need some extra info or help with the implementation.

Also if you decide not to implement this, just let me know and I will remove in progress label.

**Comment by zlzshowtime** [comment]
Hey ttu, Sorry for going dark, busy with IRL work.

Just making sure I'm tracking correctly:
The Add, Replace, Update, Delete item functionality is where we're looking to implement the JSON patch functions yeah?

**Comment by ttu** [comment]
Yes, let's implement JSON Patch only for those functions.

Move and test can be added later if needed, but those are not so commonly used, so better to start with the most used ones.

**Comment by zlzshowtime** [comment]
ok, so I have my class setup, but I am having trouble finding where would be the place for my code to get called. Mind pointing me in the right direction? I made a class in the helper class folder, if that helps

**Comment by ttu** [comment]
Can you update your code to your own branch and I can check from there what you have done so far. We then can think together some good solution.

**Comment by ttu** [comment]
@zlzshowtime Hi! I I will remove in progress label as haven't had any update from you in a while, so some one else might take this task. Just let me know if you want to continue with this and I will add in progress label back.

**Comment by maxmus** [comment]
HI @ttu. I am interested in implementing this. Can you provide more info? Should we implement it from scratch or we can use libs?

**Comment by ttu** [comment]
@maxmus Great! 

No need to make any own implementation as JsonPatch is supported by ASP.NET Core
https://docs.microsoft.com/en-us/aspnet/core/web-api/jsonpatch?view=aspnetcore-2.2#jsonpatch-in-aspnet-core

And it works with dynamic objects, so it should work nicely with used dynamic data store.
https://docs.microsoft.com/en-us/aspnet/core/web-api/jsonpatch?view=aspnetcore-2.2#dynamic-objects

Fake Server should still support current patch as well as JSON patch. I think this can be achieved by using correct Content-Types and Consume-attributes.
https://stackoverflow.com/questions/53434138/how-to-support-multiple-consumes-mime-types-in-asp-net-core-controller-method

Here are the Content-Types for current implementation
https://github.com/ttu/dotnet-fake-json-server/issues/50

**Comment by ttu** [comment]
Checked if Consume-attribute works, and it required little changes to JsonFormatter settings, so ended up implementing it (https://github.com/ttu/dotnet-fake-json-server/commit/ac0fa08b9af6249433e51d6ad40fedb1cee19420) and closed issue https://github.com/ttu/dotnet-fake-json-server/issues/50.

Adding a new method for JSON Patch with
```csharp
[Consumes("application/json-patch+json")]
```
should work without any modification to settings.

**Comment by toledotown** [comment]
Should this be implemented as a new controller?

**Comment by ttu** [comment]
@toledotown  No need to add a new controller. Add new Patch methods to DynamicController and AsyncController with different Consumes attribute.
