### ISSUE TITLE
Update intergration tests to use WebAppliationFactory 

### ISSUE THREAD

**Issue by ttu** [ttu/dotnet-fake-json-server#21]
https://docs.microsoft.com/en-us/aspnet/core/testing/integration-testing

**Comment by kashifsoofi** [comment]
Limitation, that need changes in TestHost is currently (at the time of comment) there is no way to create a client with HttpHandler with Auto Redirect set to false using TestHost.

**Comment by ttu** [comment]
@kashifsoofi  Hi. Sorry that haven't updated the Issue, but Microsoft changed practices how integration tests should be done. 

Now [WebAppliationFactory](https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-2.2#basic-tests-with-the-default-webapplicationfactory) should be used instead of TestServer. I think this changed at some point in the end of the last year.

With WebAppliationFactory AlowAutoRedirect can set to false (https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-2.2#test-a-secure-endpoint).

If you still want to finish this issue I can remove help wanted label mark it as in progess, but I understand if you dont want to continue with this anymore. 

If you have some questions about this, just let me know. I should have some sample code how test values can be injected to test server with WebAppliationFactory.

**Comment by kashifsoofi** [comment]
Thanks @ttu for the comment, almost done with the update only test now left to do is web sockets.

**Comment by ttu** [comment]
Implemented in #54
