### ISSUE TITLE
GET      /api/{object} support

### ISSUE THREAD

**Issue by vasiledoe** [ttu/dotnet-fake-json-server#26]
It works well with collections but it really needs to support JSON objects as endpoint like so:

We have data.json file:
```
`{
  "my_test_request": {
    "has_access": true,
    "token": "09832145kndse89745",
    "name": "Instagram Honey",
    "data_array": [
     "beer", "disco", "fun"
    ]
  }
}`
```

**GET http://localhost:57602/api/my_test_request**

And as response:

```
 {
    "has_access": true,
    "token": "09832145kndse89745",
    "name": "Instagram Honey",
    "data_array": [
     "beer", "disco", "fun"
    ]
  }
```

**Comment by ttu** [comment]
At the moment flat file datastore which is used to get data from JSON file supports only collections. I don't see any reason why it couldn't also support single values besides collections.

Created issue: https://github.com/ttu/json-flatfile-datastore/issues/14

After that I can add support here.

**Comment by vasiledoe** [comment]
thx for response. In the meantime just found an alternative solution, using [npm json-server](https://www.npmjs.com/package/json-server). This one supports single values as well as collections, but it need some simple installs in cmd ;)

**Comment by ttu** [comment]
Data store is now updated to version 2.0.0 which supports single items. Will add functionality now to fake server.

**Comment by ttu** [comment]
@vasiledoe implementation now in the master. Just let me know if there is something you would like to be imporved.
