### ISSUE TITLE
Add functionality - REST: Option to use Page and PageSize instead of offset and limit

### ISSUE THREAD

**Issue by ttu** [ttu/dotnet-fake-json-server#3]

**Comment by maxmus** [comment]
I would like to contribute to this issue, can you provide more info regarding this? Which method should be changed?

**Comment by ttu** [comment]
@maxmus Great! Here is more info

This is the endpoint that needs to be chaged:
https://github.com/ttu/dotnet-fake-json-server/blob/master/FakeServer/Controllers/DynamicController.cs#L70

At the moment parameters can be skip and take, or optionally offset and limit. Deciding which parameter to use comes to QueryHelper:
https://github.com/ttu/dotnet-fake-json-server/blob/master/FakeServer/Common/QueryHelper.cs#L99

Query header links and JSON object also needs to be updated:
https://github.com/ttu/dotnet-fake-json-server/blob/master/README.md#query
https://github.com/ttu/dotnet-fake-json-server/blob/master/FakeServer/Common/QueryHelper.cs#L59

You can check guidelines from GitHub how headers should look:
https://developer.github.com/v3/guides/traversing-with-pagination/

Just ask if you need some help.

**Comment by ttu** [comment]
Hi @sunithapatel !

I browsed through your implementation and it looks good. I think the best way to continue is that you make a pull request and then I can give few pointers on what could be refactored.

I think for the sake of clarity take/limit/per_page keywords should not be be interchangable, but we can continue that discussion in the PR.

**Comment by sunithapatel** [comment]
Awesome, thanks! I went ahead and made the pull request.
