### ISSUE TITLE
Reqeust to console and/or file?

### ISSUE THREAD

**Issue by alexdresko** [ttu/dotnet-fake-json-server#31]
Great job on the .NET global tool! Works great! 

Is there an option to tell fake server to simply output the request to the console or file?

If not, I'll be happy to try and help. Just point a finger in the best spot to implement the code and I'll make it happen.

**Comment by ttu** [comment]
Good that this works as a global tool 👍 

I was just checking the logging that was used and this uses [Serilog](https://github.com/serilog/serilog) for logging.

I added Serilog Console Sink to master branch, so if you want to use Console logging just change Serilog configuration
https://github.com/ttu/dotnet-fake-json-server/blob/master/FakeServer/appsettings.json#L9

How logging should be configured has changed few times with .NET Core versions so logging configuration seems to be pretty messy in this project.

Do you want to fix logging configuration so it is done as it should be with .NET Core 2.1?

**Comment by ttu** [comment]
Did some cleanup and added logging section to README

Commits:
https://github.com/ttu/dotnet-fake-json-server/commit/6120c0b082de21b1cdd9a0411ba2d4b92829d979
https://github.com/ttu/dotnet-fake-json-server/commit/aa101b17f73ba3d7919e00db8f24600f2b213772
