### ISSUE TITLE
Create new appsettings.json from command line

### ISSUE THREAD

**Issue by ttu** [ttu/dotnet-fake-json-server#48]
Add init command line parameter that will create default appsettings.json
```sh
$ fake-server --init

$ dotnet run --init
```

This command should be used with global tool as then appsettings.json is not located in the startup directory.

**Comment by seleregb** [comment]
Hi, I would like to take a run at this if you don't mind.

**Comment by seleregb** [comment]
In what directory is the appsettings.json file meant to be created?

**Comment by ttu** [comment]
Great!

File should be created to the same directory where the command is executed. 

Reason for this command is to create appsettings-file that is can be edited easily, as default appsettings.json is located in the global tools installation directory e.g. `%USERPROFILE%\.dotnet\tools\.store\fakeserver\0.10.0\fakeserver\0.10.0\tools\netcoreapp2.2\any`

**Comment by seleregb** [comment]
Okay. Is this with the settings from the default file or just a plain empty file?

**Comment by ttu** [comment]
File should have same content as default appsettings.json

**Comment by seleregb** [comment]
Please, can you walk me through how to install my local version of the package on my system? I use a Mac

**Comment by ttu** [comment]
I added a new developer notes file that has so far only the guide how to install the package from local sources :)

https://github.com/ttu/dotnet-fake-json-server/blob/master/docs/developer_notes.md#install-global-tool-from-local-sources
