### ISSUE TITLE
Add custom response

### ISSUE THREAD

**Issue by sergioprates** [ttu/dotnet-fake-json-server#51]
I need custom responses to mock an api, the functionality is like this https://github.com/typicode/json-server/issues/118

**Comment by ttu** [comment]
What kind of custom response you would need?

As this is developed with a compiled language, adding customer middlewares at runtime is not so easy task.

On basic queries it is already possible to use result objects
https://github.com/ttu/dotnet-fake-json-server#query

If you just need to be able to define results property's name to match resources name that is pretty easy to implement.

**Comment by sergioprates** [comment]
I understand, I need for example a response like this:

`{
"data": {"users": [{"id": 1}]},
"notifications": ["Test"],
"success": true
}`

All responses from my API's follow this pattern, I want return the query in data object, notifications in empty array and success property as boolean.

if we add this configuration in app settings, a custom json node where we replace the response data, it's just fine.

**Comment by ttu** [comment]
Ok, I will add custom middlware where you can define the response body as a new object in appsettings.json.

Definition will be something like this):
```json
{
  "CustomResponse" : {
    "Script" : "return new { data = _Body, success = _Context.Response.StatusCode == 200. extra = 'some more info'  };"
  }
}
```

Script will be C# code and it will have _Body string that is the Response body as a text and _Context that is the whole HttpContext. Not sure if context should be _Context or context. Have to think the implementation littlebit more.
 
```cs
return new { data = _Body, success = _Context.Response.StatusCode == 200, extra = "some more info" };
```

I will publish the implementation in few days in an own branch, so you can try it out if you want.

**Comment by ttu** [comment]
Implementation in branch: https://github.com/ttu/dotnet-fake-json-server/tree/custom-response-middleware

**Comment by sergioprates** [comment]
I have tested and is nice! Works fine! Thank you!

![image](https://user-images.githubusercontent.com/10142320/56934835-28135280-6ac4-11e9-8f55-0cbcf638f4ef.png)

**Comment by ttu** [comment]
Great! I'll update the documentation and merge the PR after that.
