### ISSUE TITLE
DELETE operations put server in Bad State

### ISSUE THREAD

**Issue by Shanjaq** [ttu/dotnet-fake-json-server#68]
DELETE /api/{collection}/{id}
succeeds only once.  If there are other collections, server will return 500.

Sample data.json:
```
{
  "tests": [
    {
      "value": [
        "Test1"
      ],
      "id": 0
    }
  ],
  "items": [
    {
      "description": "some_description",
      "createdDate": "0001-01-01T00:00:00",
      "id": 0
    }
  ],
  "programs": [
    {
      "id": 0,
      "canOverride": false,
      "enabled": true,
      "version": null
    }
  ]
}
```
Operation 1
DELETE /api/tests/0
result: 204

Operation 2
DELETE /api/items/0
result: 500

**Comment by ttu** [comment]
Thanks for the issue! Will make the fix to https://github.com/ttu/json-flatfile-datastore
