### ISSUE TITLE
Broken Auth in Swagger UI

### ISSUE THREAD

**Issue by guillaumesasdy** [ttu/dotnet-fake-json-server#71]
On branch `update-to-core-30` the endpoints under Authentification tag in Swagger UI are unusable with various symptoms on the following browsers :

- On Windows 10 with Chrome
- On Windows 10 with Firefox
- On MacOS with Chrome

Those endpoints work fine with cURL commands. The problem comes from Swagger UI.

Note: on branch `master` with .NET Core 2.2, despite the web browser receives the auth token, the Swagger UI does not display the response. Is it important to fix that, or should we focus our effort on .NET Core 3?

**Comment by guillaumesasdy** [comment]
Indeed Swagger UI do not respond well to the way the swagger.json file was generated with the use of `AddAuthorizationHeaderParameterOperationFilter` and/or `AuthTokenOperation` as you guessed correctly.

In order to make sure of that, I tested Swagger UI with a swagger.json I created manually. The UI works fine:
* with [Basic auth](https://github.com/guillaumesasdy/dotnet-fake-json-server/commit/469a1b7a87d6955329e91f5d57449a402f34ad7d#diff-f61de52af6291d42e5441f5580085682R1160)
* with [Token auth](https://github.com/guillaumesasdy/dotnet-fake-json-server/commit/1e78b6d71170113487ee13f27f917fc965e19469#diff-f61de52af6291d42e5441f5580085682R1160) with a security scheme as OAuth2. The other possible security scheme would be [HTTP](https://github.com/guillaumesasdy/dotnet-fake-json-server/commit/64a6125237ddc073fb7b01562e212cac04aa1bea#diff-f61de52af6291d42e5441f5580085682R1159). But in this case the Swagger UI is less friendly. It prompts for the token despite the user has no way to get it.

They are changes in the UI/UX:
* there is no more the Authentication tag with endpoints for authentication/logout
* a button Authorize opens a modal where user can enter its id/secret; this will set the right Authorization header for all subsequent requests. The user will not need anymore to pass around the token.

My point of view is that this change is for the best. It simplifies the use of the API for testing. Here is a screenshot:

![image](https://user-images.githubusercontent.com/1765038/75176836-36a6b680-5735-11ea-9f41-cf3c99eb5fd9.png)

[After a quick read of Swashbuckle docs](https://github.com/domaindrivendev/Swashbuckle.AspNetCore#add-security-definitions-and-requirements) I think I can generate a similar swagger.json using `AddSecurityRequirement` in configuration.

@ttu  Is it fine for you if I go this way?

**Comment by ttu** [comment]
Thanks for the inspecting the issue.

Using `AddSecurityDefinition` is the normal way to add authentication to Swagger. Not sure why I didn't go that way in the beginning. Maybe wanted to have authentication endpoints visible from Swagger so it is more clear for people who are not familiar with Swagger what kind of functionality backend provides. Or just couldn't get it working any other way... Can't be sure anymore 😄 

Yes, try to add authentication by configuring Swashbucle 👍 . Logout endpoint might still be needed as blacklisting the tokens is a custom functionality. Swagger logout doesn't call that endpoint by default.

**Comment by guillaumesasdy** [comment]
@ttu I let you know that I'll have time to work on it this week-end :)

**Comment by ttu** [comment]
Fixed in https://github.com/ttu/dotnet-fake-json-server/commit/e236100db243d8501e34d5e50818c73bbfd92c65
