### ISSUE TITLE
Add Swagger URL  to startup output 

### ISSUE THREAD

**Issue by ttu** [ttu/dotnet-fake-json-server#81]
Current output
```sh
Datastore file: datastore.json
Datastore location: /home/tomi/src/github/dotnet-fake-json-server/FakeServer
Static files: default wwwroot
Hosting environment: Development
Content root path: /home/xxxx/dotnet-fake-json-server/FakeServer
Now listening on: http://localhost:57603
Application started. Press Ctrl+C to shut down.
```

Add Swagger Open API as a last line.
```sh
Now listening on: http://localhost:57603
Application started. Press Ctrl+C to shut down.
Swagger Open API is available on: http://localhost:57603/swagger  
```

Pretty likely this needs to be done in `Startup.cs` as we need to be able to check what is the current port in use.

**Comment by s-a-n-i-n** [comment]
Would turning off default .net core startup messaging and logging out to console manually be acceptable?
AFAIK, you want to inject line between two default core startup messages ("now listening" and "app started") which is not possible.

**Comment by ttu** [comment]
Hi. Forgot that those 2 lines are from framework.

No need to do any extra work by configuring messages.  Swagger-line can be after Content root path-line and before those default .net core startup messages.

**Comment by ttu** [comment]
Updated the description, as we need to read the current port and maybe that is easiest to do in `Startup.cs`.
