### ISSUE TITLE
If a key with an empty array value exists in the data source, the api /collectionId endpoint returns the NotFound state.

### ISSUE THREAD

**Issue by minamoeini** [ttu/dotnet-fake-json-server#87]
When there is an empty collection in JSON file, we can get it as a Key by using the Get all endpoint, but api/collectionId endpoint returns notfound status and it is confusing.

The minor change could be that if collection's count in this function (collection = _ds.GetCollection (collectionId)) is 0, the endpoint should return empty array as a result

**Comment by ttu** [comment]
Hi! Thanks for the issue.

This is a good point, can't remember why I did originally choose to return 404 for empty collections.
Fix: https://github.com/ttu/dotnet-fake-json-server/pull/88
